### ISSUE TITLE
Add "N" 次受付 view for Single

### ISSUE THREAD

**Issue by kuboRocks** [universallyleo/ngzkHandshakeTable#3]
For now, we only able to check the last "受付結果" record of each Single. Could you add a way to check back the previous sell records?

And the "過去との差" comparison view, it is missing Total sold stats.

**Comment by universallyleo** [comment]
I added N次受付 for record viewing.

Not sure what you want for comparison view?  A picture would be helpful.

**Comment by kuboRocks** [comment]
Nice. This way I able to figure out the data quickly.

Mainly, I need these data for prediction and discussion. With total number that's easier to tell the diff


highlighted in BLUE
![Screenshot 2024-04-11 131801](https://github.com/universallyleo/ngzkHandshakeTable/assets/110786658/8715f3f7-74a0-4620-86c9-146770188cc0)

**Comment by universallyleo** [comment]
Done!

First feature was something I should have done long time ago, thank you for pushing me to finally complete it.
